In [51]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix

In [9]:

# Specify the file path
file_path = 'C:/Users/reyta/OneDrive/Documents/PhD/Python/adult/adult.data'

# Define column names (you can find these in the dataset documentation)
columns = ['age', 'workclass', 'fnlwgt', 'education', 'education-num', 
           'marital-status', 'occupation', 'relationship', 'race', 'sex', 
           'capital-gain', 'capital-loss', 'hours-per-week', 'native-country', 'income']

# Read the .data file
df = pd.read_csv(file_path, header=None, names=columns, skipinitialspace=True)

df

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [21]:
unique_values = df['income'].unique()
print(unique_values)

['<=50K' '>50K']

In [ ]:
X=iris.data
y=iris.target
df=pd.DataFrame(X, columns=iris.feature_names)
print(df.head())
print(len(df))

In [27]:
#KNN MODEL PREDICTION ONE'S INCOME GROUP BASED ON THEIR WORKING HOURS PER WEEK AND TOTAL YEARS OF EDUCATION
X = df[['education-num', 'hours-per-week']]  
y = df['income']  

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


knn = KNeighborsClassifier(n_neighbors=5)  
knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

       <=50K       0.80      0.95      0.87      4942
        >50K       0.60      0.24      0.34      1571

    accuracy                           0.78      6513
   macro avg       0.70      0.59      0.60      6513
weighted avg       0.75      0.78      0.74      6513

In [41]:
#CROSS VALIDATION OF KNN MODEL
X_scaled = scaler.fit_transform(X)


cv_scores = cross_val_score(knn, X_scaled, y, cv=5)  

cv_scores

array([0.74788884, 0.73617936, 0.74278256, 0.74616093, 0.74907862])

In [53]:
X2 = df[['education-num', 'hours-per-week']]  
y2 = df['income']  

X_scaled2 = scaler.fit_transform(X)

X_train2, X_test2, y_train2, y_test2 = train_test_split(X_scaled2, y2, test_size=0.2, random_state=42)

model2 = LogisticRegression()
model2.fit(X_train2, y_train2)

y_pred2 = model2.predict(X_test2)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test2, y_pred2))

[[4692  250]
 [1201  370]]
              precision    recall  f1-score   support

       <=50K       0.79      0.96      0.87      4942
        >50K       0.63      0.22      0.33      1571

    accuracy                           0.78      6513
   macro avg       0.71      0.59      0.60      6513
weighted avg       0.75      0.78      0.74      6513

In [59]:
#CROSS VALIDATION OF lOG REG MODEL MODEL
cv_scores2 = cross_val_score(model2, X_scaled2, y2, cv=5)

cv_scores2

array([0.78335636, 0.78224816, 0.77779484, 0.78393735, 0.78363022])

In [63]:
from sklearn.svm import SVC
X3 = df[['education-num', 'hours-per-week']]
y3 = df['income']


X_scaled3 = scaler.fit_transform(X3)

X_train3, X_test3, y_train3, y_test3 = train_test_split(X_scaled3, y3, test_size=0.2, random_state=42)

model3 = SVC(kernel='linear')  # Linear kernel for simplicity
model3.fit(X_train3, y_train3)

y_pred3 = model3.predict(X_test3)

print(confusion_matrix(y_test3, y_pred3))
print(classification_report(y_test3, y_pred3))

[[4942    0]
 [1571    0]]
              precision    recall  f1-score   support

       <=50K       0.76      1.00      0.86      4942
        >50K       0.00      0.00      0.00      1571

    accuracy                           0.76      6513
   macro avg       0.38      0.50      0.43      6513
weighted avg       0.58      0.76      0.65      6513

C:\Users\reyta\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\reyta\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\reyta\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [65]:
#CROSS VALIDATION OF lOG REG MODEL MODEL
cv_scores3 = cross_val_score(model3, X_scaled3, y3, cv=5)

cv_scores3

array([0.75909719, 0.75921376, 0.75921376, 0.75921376, 0.75921376])

In [ ]:
#Interpretation of the applied models is added as Assignment6_report into the repository